---
Name: productcomparison
After: 'silvershop/*'
---
SilverShop\Page\Product:
  extensions:
    - 'SilverStripe\Comparison\ProductFeaturesExtension'
Product_Controller:
  extensions:
    - 'ProductControllerFeaturesExtension'
ProductCatalogAdmin:
  managed_models:
    - 'Product'
    - 'ProductCategory'
    - 'Feature'
    - 'FeatureGroup'

LeftAndMain:
  extra_requirements_javascript:
    - shop_comparison/javascript/shop_Comparison_admin.js
